[package]
name = "multiwii_serial_protocol"
version = "0.1.0"
authors = ["Rudi Benkovic <rudi.benkovic@gmail.com>"]

[dependencies]
packed_struct = "^0.1.0"
packed_struct_codegen = "^0.1.0"
serde = "1.0"
serde_derive = "1.0"

[features]
default = ["std"]
std = []
no_std = []